### ISSUE TITLE
ディレクトリ構成の変更

### ISSUE THREAD

**Issue by atsushieno** [dotnetreadingjp/coreclr-botr-jp#2]
画像ファイルのリンクをそのままにして使い回したいので（ですよね）、coreclr/Documentationディレクトリをこちらのトップにして、botrディレクトリを作成してそこに訳文を移動しようと思いますがどうでしょう > @yfakariya

**Comment by yfakariya** [comment]
そうしましょう。

**Comment by atsushieno** [comment]
done.
